#ifdef _WIN32
#include "xinu_windows_compat.h"
#endif

#ifndef _XINU_H_
#define _XINU_H_

/*
 * xinu.h - Main XINU header file
 */

// 1. SYSTEM HEADERS FOR STANDARD TYPES (like int32_t, size_t)
#include <stddef.h>
#ifndef _WIN32
#include <stdint.h>
#else
/* Windows uses its own int types */
#endif

// 2. XINU'S OWN FUNDAMENTAL, MINIMAL DEFINITIONS (Generated by go.sh in root)
#include "xinu_stddefs.h" // This path assumes xinu_stddefs.h is in the project root
#include <xinu.h>

// 3. XINU'S TYPEDEFS THAT MAY USE THE SYSTEM TYPES
typedef int32_t  int32;
typedef uint32_t uint32;
typedef int16_t  int16;
typedef uint16_t uint16;
typedef int8_t   int8;
typedef uint8_t  uint8;

typedef int16  qid16;
typedef int32  pid32;
typedef int32  sid32;
typedef int32  bpid32;

typedef unsigned char bool8;

// [[[ BEGIN DYNAMIC XINU MODULE INCLUDES - DO NOT EDIT MANUALLY ]]]
// This section will be auto-generated by go.sh
// Manual additions here will be overwritten!
// Example of what might be generated:
// #include <kernel.h>
// #include <conf.h>
// ... etc.
// [[[ END DYNAMIC XINU MODULE INCLUDES ]]]

// Any other definitions that should come AFTER all module headers
#ifndef TRUE
#define TRUE    1
#endif
#ifndef FALSE
#define FALSE   0
#endif

/* Include all other header files */
/// [[[ BEGIN DYNAMIC XINU MODULE INCLUDES ]]]
#include <bufpool.h>
#include <clock.h>
#include <conf.h>
#include <ctype.h>
#include <date.h>
#include <device.h>
#include <i386.h>
#include <icu.h>
#include <interrupt.h>
#include <kernel.h>
#include <mark.h>
#include <memory.h>
#include <pci.h>
#include <ports.h>
#include <process.h>
#include <prototypes.h>
#include <pstarv.h>
#include <queue.h>
#include <sched.h>
#include <semaphore.h>
#include <shell.h>
#include <sscanf_fix.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <tty.h>
#include <uart.h>
/// [[[ END DYNAMIC XINU MODULE INCLUDES ]]]

#endif /* _XINU_H_ */
