/* initialize_system.c - Initialize the XINU simulation environment
 * Generated on: 2025-06-16 02:14:38
 * Generated by: mol
 */

#include "xinu_includes.h"

/* Global variables needed for simulation */
volatile uint32 clktime = 0;
volatile uint32 clkticks = 0;
struct procent proctab[NPROC];
pid32 pstarv_pid = BADPID;
bool8 enable_starvation_fix = TRUE;
uint32 pstarv_ready_time = 0;
uint32 last_boost_time = 0;
qid16 readylist;
pid32 currpid = 0;
uint32 preempt = QUANTUM;
struct defer Defer = {0, FALSE};

/*
 * initialize_system - Initialize the system variables for simulation
 */
void initialize_system(void) {
    /* Initialize process table */
    int i;
    for (i = 0; i < NPROC; i++) {
        proctab[i].prstate = PR_FREE;
        proctab[i].prprio = 0;
        proctab[i].prname[0] = '\0';
    }
    
    /* Initialize other system variables */
    clktime = 0;
    clkticks = 0;
    pstarv_pid = BADPID;
    enable_starvation_fix = TRUE;
    pstarv_ready_time = 0;
    last_boost_time = 0;
    currpid = 0;
    preempt = QUANTUM;
    Defer.ndefers = 0;
    Defer.attempt = FALSE;
}

/* Sleep function for simulation (Windows compatible) */
void Sleep(uint32 ms) {
    ::Sleep(ms);
    update_system_time();
}
