/* xinu_stddefs.h - Generated by go.sh */
#ifndef _XINU_STDDEFS_H_
#define _XINU_STDDEFS_H_
typedef void exchandler; typedef int message;
/* Add other very basic, self-contained XINU typedefs here if needed */
/* For example: typedef int int32; if not using <stdint.h> directly in xinu.h */
#endif /* _XINU_STDDEFS_H_ */
