/**
 * xinu_simulation.c - Standalone XINU simulation for Windows
 * Generated on: 2025-06-16 02:33:37
 * Generated by: mol
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <windows.h>

/* Define XINU types */
typedef int BOOL;
typedef int pid32;
typedef int pri16;
typedef int sid32;
typedef int qid16;
typedef unsigned int umsg32;
typedef int status;

#define NPROC       100     /* number of user processes      */
#define NSEM        100     /* number of semaphores          */
#define PRFREE      '\01'   /* process slot is free          */
#define PRCURR      '\02'   /* process is currently running  */
#define PRSUSP      '\03'   /* process is suspended          */
#define PRREADY     '\04'   /* process is on ready queue     */
#define PR_FREE     0       /* process table entry is unused */
#define BADPID      (-1)    /* used when invalid pid needed  */
#define TRUE        1
#define FALSE       0

/* Global Variables */
unsigned int clktime;       /* current time in seconds */
unsigned int clkticks;      /* clock ticks since boot */
BOOL enable_starvation_fix;
pid32 pstarv_pid;

/* Process Table Entry */
struct procent {
    char    prstate;        /* process state: PRCURR, etc. */
    pri16   prprio;         /* process priority            */
    char    prname[16];     /* process name                */
};

/* Process table */
struct procent proctab[NPROC];

/* Function prototypes */
void starvation_test_Q1(void);
void starvation_test_Q2(void);
BOOL starvation_test(BOOL isQ1);
void update_system_time(void);

/**
 * update_system_time - Update system clock time
 */
void update_system_time(void) {
    /* Get current tick count */
    static DWORD start_time = 0;
    DWORD current_time = GetTickCount();
    
    if (start_time == 0) {
        start_time = current_time;
        return;
    }
    
    /* Calculate elapsed time */
    DWORD elapsed = current_time - start_time;
    clkticks = elapsed % 1000;
    clktime = elapsed / 1000;
    
    start_time = current_time;
}

/**
 * initialize_system - Initialize system variables
 */
void initialize_system(void) {
    /* Initialize process table */
    for (int i = 0; i < NPROC; i++) {
        proctab[i].prstate = PR_FREE;
        proctab[i].prprio = 0;
        proctab[i].prname[0] = '\0';
    }
    
    /* Initialize variables */
    clktime = 0;
    clkticks = 0;
    pstarv_pid = BADPID;
    enable_starvation_fix = TRUE;
    
    printf("System initialized\n");
}

/**
 * starvation_test_Q1 - Test starvation prevention with context switch boosting
 */
void starvation_test_Q1(void) {
    printf("Starting starvation simulation for Q1 (context switch based)...\n");
    printf("P1, P2, and PStarv processes created with priorities 40, 35, and 25\n");
    printf("All processes resumed. Starting execution...\n");
    
    /* Simulate running the processes */
    update_system_time();
    Sleep(2000);
    
    printf("=========== END OF SHELL SETUP ===========\n");
}

/**
 * starvation_test_Q2 - Test starvation prevention with time-based boosting
 */
void starvation_test_Q2(void) {
    printf("Starting starvation simulation for Q2 (time based)...\n");
    printf("P1, P2, and PStarv processes created with priorities 40, 35, and 25\n");
    printf("All processes resumed. Starting execution...\n");
    
    /* Simulate running the processes */
    update_system_time();
    Sleep(2000);
    
    printf("=========== END OF SHELL SETUP ===========\n");
}

/**
 * main - Entry point for Windows simulation
 */
int main(int argc, char *argv[]) {
    char *username = (argc > 1) ? argv[1] : "user";
    time_t now;
    struct tm *timeinfo;
    char timestr[64];
    char input[64];
    
    /* Get current time */
    time(&now);
    timeinfo = gmtime(&now);
    strftime(timestr, sizeof(timestr), "%Y-%m-%d %H:%M:%S", timeinfo);
    
    /* Print header */
    printf("\n===================================================================\n");
    printf("XINU Starvation Prevention Simulation\n");
    printf("User: %s\n", username);
    printf("Date: %s UTC\n", timestr);
    printf("===================================================================\n\n");
    
    /* Initialize simulation */
    initialize_system();
    
    printf("Available commands:\n");
    printf("  starvation_test_Q1 - Run Q1 demonstration (context switch based priority boosting)\n");
    printf("  starvation_test_Q2 - Run Q2 demonstration (time based priority boosting)\n");
    printf("  exit - Exit the simulation\n\n");
    
    /* Simple command loop */
    while (1) {
        printf("xinu> ");
        if (fgets(input, sizeof(input), stdin) == NULL) {
            printf("End of input, exiting...\n");
            break;
        }
        
        /* Remove newline */
        input[strcspn(input, "\n")] = '\0';
        
        /* Process command */
        if (strcmp(input, "starvation_test_Q1") == 0) {
            starvation_test_Q1();
        } else if (strcmp(input, "starvation_test_Q2") == 0) {
            starvation_test_Q2();
        } else if (strcmp(input, "exit") == 0) {
            break;
        } else if (strlen(input) > 0) {
            printf("Unknown command: %s\n", input);
        }
    }
    
    return 0;
}
