/* xinu_simulation_win.c - Windows wrapper for XINU simulation
 * Generated on: 2025-06-16 02:26:24
 * Generated by: mol
 * This file implements Windows-specific functions for XINU simulation
 */

/* Include Windows headers before any XINU code */
#include <windows.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

/* These are needed for the simulation */
#include "xinu_includes.h"

/* Global variables for simulation */
DWORD start_tick_count = 0;

/* 
 * update_system_time - Sync Windows time to XINU time
 */
void update_system_time(void) {
    DWORD current_tick = GetTickCount();
    
    if (start_tick_count == 0) {
        start_tick_count = current_tick;
        return;
    }
    
    DWORD elapsed = current_tick - start_tick_count;
    clkticks += elapsed % 1000;
    clktime += elapsed / 1000;
    
    start_tick_count = current_tick;
}

/*
 * Win32Sleep - Sleep wrapper that updates XINU time
 */
void Win32Sleep(DWORD ms) {
    Sleep(ms);
    update_system_time();
}

/*
 * initialize_simulation - Initialize the Windows simulation
 */
void initialize_simulation(void) {
    /* Initialize timing */
    start_tick_count = GetTickCount();
    
    /* Initialize XINU system */
    initialize_system();
    
    printf("Windows simulation environment initialized\n");
}

/* 
 * windows_main - Entry point for Windows simulation
 */
int windows_main(int argc, char *argv[]) {
    char *username = (argc > 1) ? argv[1] : "user";
    time_t now;
    struct tm *timeinfo;
    char timestr[64];
    
    /* Get current time */
    time(&now);
    timeinfo = gmtime(&now);
    strftime(timestr, sizeof(timestr), "%Y-%m-%d %H:%M:%S", timeinfo);
    
    /* Print header */
    printf("\n===================================================================\n");
    printf("XINU Starvation Prevention Simulation\n");
    printf("User: %s\n", username);
    printf("Date: %s UTC\n", timestr);
    printf("===================================================================\n\n");
    
    /* Initialize simulation environment */
    initialize_simulation();
    
    /* Call the main XINU function */
    xinu_main();
    
    return 0;
}

/* 
 * main - Windows entry point that calls our wrapper
 */
int main(int argc, char *argv[]) {
    return windows_main(argc, argv);
}
