/* xinu_includes.h - Wrapper for XINU code compilation.
 * Generated by xinu_generator.py
 * Generated on: 2025-06-16 16:47:05
 * By user: mod
 */
#ifndef _XINU_INCLUDES_SIM_WRAPPER_H_
#define _XINU_INCLUDES_SIM_WRAPPER_H_

/* Include standard headers first */
#include <stdarg.h>
#include <stddef.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>

/* Define platform-specific macros to help with compatibility */
#define XINU_SIM_MODE 1

/* Prevent duplicate definitions */
#ifdef NULL
#undef NULL
#endif

#ifdef OK
#undef OK
#endif

#ifdef SYSERR
#undef SYSERR
#endif

#ifdef EOF
#undef EOF
#endif

#ifdef BADPID
#undef BADPID
#endif

#ifdef SHELL_OK
#undef SHELL_OK
#endif

#ifdef SHELL_ERROR
#undef SHELL_ERROR
#endif

/* Add devcall type definition before including xinu.h */
typedef int devcall;

/* Now include XINU headers */
#include "xinu.h" 
#include "xinu_sim_declarations.h"

/* --- AGGRESSIVE SHIMS --- */
#ifdef getchar
#undef getchar
#endif
#define getchar() xinu_getchar_sim_redirect()
#ifdef putchar
#undef putchar
#endif
#define putchar(c) xinu_putchar_sim_redirect(c)

#define printf xinu_printf_sim_redirect
#define fprintf xinu_fprintf_sim_redirect
#define sprintf xinu_sprintf_sim_redirect
#define scanf xinu_scanf_sim_redirect
#define fscanf xinu_fscanf_sim_redirect
#define sscanf xinu_sscanf_sim_redirect
#define fgetc xinu_fgetc_sim_redirect
#define fgets xinu_fgets_sim_redirect
#define fputc xinu_fputc_sim_redirect
#define fputs xinu_fputs_sim_redirect

#define _doprnt xinu_doprnt_sim_redirect
#define _doscan xinu_doscan_sim_redirect

#ifdef abs
#undef abs
#endif
#define abs(n) xinu_abs_sim_redirect(n)
#ifdef labs
#undef labs
#endif
#define labs(n) xinu_labs_sim_redirect(n)

#define atoi(s) xinu_atoi_sim_redirect(s)
#define atol(s) xinu_atol_sim_redirect(s)

#ifdef rand
#undef rand
#endif
#define rand() xinu_rand_sim_redirect()
#ifdef srand
#undef srand
#endif
#define srand(s) xinu_srand_sim_redirect(s)

#ifdef qsort
#undef qsort
#endif
#define qsort(b,n,s,c) xinu_qsort_sim_redirect(b,n,s,c)

#define strcpy xinu_strcpy_sim_redirect
#define strncpy xinu_strncpy_sim_redirect
#define strcat xinu_strcat_sim_redirect
#define strncat xinu_strncat_sim_redirect
#define strcmp xinu_strcmp_sim_redirect
#define strncmp xinu_strncmp_sim_redirect
#define strlen xinu_strlen_sim_redirect
#define strnlen xinu_strnlen_sim_redirect
#define strchr xinu_strchr_sim_redirect
#define strrchr xinu_strrchr_sim_redirect
#define strstr xinu_strstr_sim_redirect
#define memcpy xinu_memcpy_sim_redirect
#define memmove xinu_memmove_sim_redirect
#define memcmp xinu_memcmp_sim_redirect
#define memset xinu_memset_sim_redirect

/* Define kprintf as printf for simulation */
#define kprintf printf

#endif /* _XINU_INCLUDES_SIM_WRAPPER_H_ */
