/* xinu_includes.h - Isolation layer for XINU simulation
 * Generated on: 2025-06-16 02:26:24
 * Generated by: mol
 */

#ifndef _XINU_INCLUDES_H_
#define _XINU_INCLUDES_H_

/* Prevent Windows headers from being included inside XINU code */
#define _WINDOWS_
#define _INC_WINDOWS
#define _WINSOCK2API_
#define _WINBASE_

/* Windows types mapped to XINU types to prevent conflicts */
#define VOID void
#define DWORD unsigned long
#define HANDLE void*
#define HWND void*

/* Function prototypes for simulation */
extern void initialize_system(void);
extern void update_system_time(void);
extern void Win32Sleep(unsigned long ms);

/* Define XINU simulation macro */
#define XINU_SIMULATION

/* Now include actual XINU headers */
#include "xinu.h"

#endif /* _XINU_INCLUDES_H_ */
