/* xinu_core.c - Minimal XINU core for simulation 
 * Generated by xinu_generator.py
 * Generated on: 2025-06-17 00:36:34
 * By user: mod
 */
#include "xinu_includes.h"

/* Global system variables */
pid32 currpid = 0;               /* Currently executing process ID   */
unsigned long clktime = 0;       /* Current time in seconds since boot */
unsigned long count1000 = 0;     /* Milliseconds since last second */

/* Process table */
struct procent proctab[20];      /* Simple process table with 20 entries */

/* Main function */
int main(int argc, char *argv[]) {
    printf("XINU Simulation Starting\n");
    printf("Generated by %s on %s\n", "mod", "2025-06-17 00:36:34");
    
    /* Initialize process table */
    for (int i = 0; i < 20; i++) {
        proctab[i].prstate = PR_FREE;
        sprintf(proctab[i].prname, "proc%d", i);
        proctab[i].prio = 10;
        proctab[i].quantum = 100;
    }
    
    printf("XINU Simulation Ready\n");
    
    /* Add your test code here */
    
    return 0;
}
