/* xinu_includes.h - Dynamically generated by xinu_generator.py on 2025-06-17 21:39:55 */
/* User: mol */
#ifndef _XINU_INCLUDES_H_
#define _XINU_INCLUDES_H_

/* Include local definition file */
#include "xinu_stddefs.h"

/* Standard C includes */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>

/* XINU OS structures needed for simulation */
{{ system_structures }}

/* External declarations for system variables */
{{ system_variables }}

/* Process table entry */
{{ process_structure }}

/* External process table declaration */
extern struct procent proctab[];

/* Additional structures required for simulation */
{{ additional_structures }}

#endif /* _XINU_INCLUDES_H_ */