/* xinu_sim_declarations.h - Declarations for simulation functions
 * Generated by {{ generator }}
 * Generated on: {{ timestamp }}
 * By user: {{ user }}
 */
#ifndef _XINU_SIM_DECLARATIONS_H_
#define _XINU_SIM_DECLARATIONS_H_

/* Include standard headers first to ensure types like FILE are defined */
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <stddef.h>

/* Function pointer typedefs for XINU-specific callbacks */
typedef int (*xinu_putc_func_t)(int, int);
typedef int (*xinu_doscan_getc_func_t)(int);
typedef int (*xinu_doscan_ungetc_func_t)(int, int);
typedef int (*xinu_qsort_cmp_t)(const void*, const void*);

/* Standard IO redirects */
extern int xinu_printf_sim_redirect(const char *format, ...);
extern int xinu_fprintf_sim_redirect(void *stream, const char *format, ...);
extern int xinu_sprintf_sim_redirect(char *buffer, const char *format, ...);
extern int xinu_scanf_sim_redirect(const char *format, ...);
extern int xinu_fscanf_sim_redirect(void *stream, const char *format, ...);
extern int xinu_sscanf_sim_redirect(const char *buffer, const char *format, ...);
extern int xinu_getchar_sim_redirect(void);
extern int xinu_putchar_sim_redirect(int c);
extern int xinu_fgetc_sim_redirect(void *stream);
extern char* xinu_fgets_sim_redirect(char *str, int num, void *stream);
extern int xinu_fputc_sim_redirect(int c, void *stream);
extern int xinu_fputs_sim_redirect(const char *str, void *stream);

/* Format string handlers */
extern int xinu_doprnt_sim_redirect(char *fmt, va_list ap, xinu_putc_func_t putc_func, int putc_arg);
extern int xinu_doscan_sim_redirect(char *fmt, va_list ap, xinu_doscan_getc_func_t getc_func, 
                             xinu_doscan_ungetc_func_t ungetc_func, int getc_arg, int ungetc_arg);

/* Standard Library redirects */
extern int xinu_abs_sim_redirect(int n);
extern long xinu_labs_sim_redirect(long n);
extern int xinu_atoi_sim_redirect(const char *str);
extern long xinu_atol_sim_redirect(const char *str);
extern int xinu_rand_sim_redirect(void);
extern void xinu_srand_sim_redirect(unsigned int seed);
extern void xinu_qsort_sim_redirect(void *base, size_t num, size_t size, xinu_qsort_cmp_t compare);

/* String handling redirects */
extern char* xinu_strcpy_sim_redirect(char *dest, const char *src);
extern char* xinu_strncpy_sim_redirect(char *dest, const char *src, size_t n);
extern char* xinu_strcat_sim_redirect(char *dest, const char *src);
extern char* xinu_strncat_sim_redirect(char *dest, const char *src, size_t n);
extern int xinu_strcmp_sim_redirect(const char *s1, const char *s2);
extern int xinu_strncmp_sim_redirect(const char *s1, const char *s2, size_t n);
extern size_t xinu_strlen_sim_redirect(const char *s);
extern size_t xinu_strnlen_sim_redirect(const char *s, size_t maxlen);
extern char* xinu_strchr_sim_redirect(const char *s, int c);
extern char* xinu_strrchr_sim_redirect(const char *s, int c);
extern char* xinu_strstr_sim_redirect(const char *haystack, const char *needle);
extern void* xinu_memcpy_sim_redirect(void *dest, const void *src, size_t n);
extern void* xinu_memmove_sim_redirect(void *dest, const void *src, size_t n);
extern int xinu_memcmp_sim_redirect(const void *s1, const void *s2, size_t n);
extern void* xinu_memset_sim_redirect(void *s, int c, size_t n);

/* Simulation helpers */
extern void xinu_simulation_yield(void);
extern void xinu_trigger_clock_interrupt(void);

#endif /* _XINU_SIM_DECLARATIONS_H_ */