/* xinu.h - Dynamically generated by xinu_generator.py on 2025-06-17 21:16:52 */
/* User: mol */
#ifndef _XINU_H_
#define _XINU_H_

/* Include XINU standard definitions */
#include "../output/xinu_stddefs.h"

/* Include standard C headers */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>

/* Process table declarations */
{{ process_declarations }}

/* External declarations for system variables */
extern pid32 currpid;        /* Currently executing process ID         */
extern unsigned long clktime;/* Current time in seconds since boot     */
extern unsigned long count1000;/* Milliseconds since last clock tick   */

/* Function prototypes */
{{ function_prototypes }}

/* Include all other header files */
/// [[[ BEGIN DYNAMIC XINU MODULE INCLUDES ]]]
{{ dynamic_includes }}
/// [[[ END DYNAMIC XINU MODULE INCLUDES ]]]

#endif /* _XINU_H_ */