/* xinu_core.c - Minimal XINU core for simulation 
 * Generated by xinu_generator.py
 * Generated on: 2025-06-17 14:41:22
 * By user: mod
 */
#include "xinu_includes.h"

/* Forward declarations for shell commands */
extern int starvation_test(int argc, char *argv[]);
extern int starvation_test2(int argc, char *argv[]);

/* Global system variables */
pid32 currpid = 0;               /* Currently executing process ID   */
unsigned long clktime = 0;       /* Current time in seconds since boot */
unsigned long count1000 = 0;     /* Milliseconds since last second */

/* Process table */
struct procent proctab[20];      /* Simple process table with 20 entries */

/* Main function */
int main(int argc, char *argv[]) {
    printf("XINU Simulation Starting\n");
    printf("Generated by %s on %s\n", getenv("USER") ? getenv("USER") : "unknown", 
           __DATE__ " " __TIME__);
    
    /* Initialize process table */
    for (int i = 0; i < 20; i++) {
        proctab[i].prstate = PR_FREE;
        sprintf(proctab[i].prname, "proc%d", i);
        proctab[i].prio = 10;
        proctab[i].quantum = 100;
    }
    
    printf("XINU Simulation Ready\n");
    
    /* Process command line arguments for starvation tests */
    if (argc > 1) {
        if (strcmp(argv[1], "test1") == 0) {
            printf("Running starvation_test_Q1\n");
            return starvation_test(1, argv);
        } else if (strcmp(argv[1], "test2") == 0) {
            printf("Running starvation_test_Q2\n");
            return starvation_test2(1, argv);
        } else {
            printf("Unknown command: %s\n", argv[1]);
            printf("Available commands:\n");
            printf("  test1 - Run starvation test Q1\n");
            printf("  test2 - Run starvation test Q2\n");
        }
    }
    
    return 0;
}
