/* xinu_stddefs.h - Generated by xinu_generator.py
 * Generated on: 2025-06-17 00:36:34
 * By user: mod
 */
#ifndef _XINU_STDDEFS_H_
#define _XINU_STDDEFS_H_

/* Basic XINU type definitions */
typedef void exchandler;
typedef int message;
typedef int syscall;
typedef int process;
typedef int int32;
typedef unsigned int uint32;
typedef int bool32;
typedef int did32;
typedef int pid32;
typedef int status;

/* Only define these if not already defined in xinu.h */
#ifndef PR_FREE
/* Process state constants */
#define PR_FREE      0       /* Process table entry is unused              */
#define PR_CURR      1       /* Process is currently running               */
#define PR_READY     2       /* Process is on ready queue                  */
#define PR_RECV      3       /* Process waiting for message                */
#define PR_SLEEP     4       /* Process is sleeping                        */
#define PR_SUSP      5       /* Process is suspended                       */
#define PR_WAIT      6       /* Process is on semaphore queue              */
#define PR_RECTIM    7       /* Process is receiving with timeout          */
#endif

/* These are defined in xinu.h, so we'll avoid redefining them */
#ifndef OK
#define OK            1      /* System call returns OK                     */
#endif
#ifndef SYSERR
#define SYSERR       -1      /* System call returns error                  */
#endif
#ifndef SHELL_OK
#define SHELL_OK      1      /* Shell command returns OK                   */
#endif
#ifndef SHELL_ERROR
#define SHELL_ERROR  -1      /* Shell command returns error                */
#endif
#ifndef BADPID
#define BADPID       -1      /* Error process ID                           */
#endif

/* These might also be defined elsewhere */
#ifndef NULL
#define NULL         0       /* Null pointer                               */
#endif
#ifndef EOF
#define EOF         -2       /* End-of-file                                */
#endif

#endif /* _XINU_STDDEFS_H_ */
