/* xinu_sim_declarations.h - Dynamically generated by xinu_generator.py on 2025-06-17 21:39:55 */
/* User: mol */
#ifndef _XINU_SIM_DECLARATIONS_H_
#define _XINU_SIM_DECLARATIONS_H_

// Standard includes for simulation
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>

// Standard I/O function redirects
{{ stdio_functions }}

// Standard library function redirects
{{ stdlib_functions }}

// String and memory function redirects
{{ string_functions }}

// Process management functions
{{ process_management }}

// Interrupt management functions
{{ interrupt_management }}

// Additional simulation functions
{{ simulation_functions }}

// Dynamically detected functions from XINU OS
{{ dynamic_functions }}

#endif /* _XINU_SIM_DECLARATIONS_H_ */