/* xinu_stddefs.h - Generated by g++ preprocessing */
/* Generated on: 2025-06-17 22:51:56 */
/* By user: mol */
#ifndef _XINU_STDDEFS_H_
#define _XINU_STDDEFS_H_

/* Basic type definitions */
typedef int32 pid32;
typedef int32 sid32;
typedef int ptrdiff_t;
typedef unsigned int size_t;
typedef struct {
  long long __max_align_ll __attribute__((__aligned__(__alignof__(long long))));
  long double __max_align_ld __attribute__((__aligned__(__alignof__(long double))));
} max_align_t;
typedef decltype(nullptr) nullptr_t;
typedef short unsigned int wint_t;
typedef signed char int8_t;
typedef unsigned char uint8_t;
typedef short int16_t;
typedef unsigned short uint16_t;
typedef int int32_t;
typedef unsigned uint32_t;
typedef long long int64_t;
typedef unsigned long long uint64_t;
typedef signed char int_least8_t;
typedef unsigned char uint_least8_t;
typedef short int_least16_t;
typedef unsigned short uint_least16_t;
typedef int int_least32_t;
typedef unsigned uint_least32_t;
typedef long long int_least64_t;
typedef unsigned long long uint_least64_t;
typedef signed char int_fast8_t;
typedef unsigned char uint_fast8_t;
typedef short int_fast16_t;
typedef unsigned short uint_fast16_t;
typedef int int_fast32_t;
typedef unsigned int uint_fast32_t;
typedef long long int_fast64_t;
typedef unsigned long long uint_fast64_t;
typedef int __intptr_t;
typedef __intptr_t intptr_t;
typedef unsigned int __uintptr_t;
typedef __uintptr_t uintptr_t;
typedef long long intmax_t;
typedef unsigned long long uintmax_t;
typedef int int32;
typedef unsigned int uint32;
typedef short int16;
typedef unsigned short uint16;
typedef char int8;
typedef unsigned char uint8;
typedef int16 qid16;
typedef int32 bpid32;
typedef byte bool8;
typedef unsigned char byte;
typedef unsigned int word;
typedef unsigned long dword;
typedef unsigned long long uint64;
typedef int32 did32;
typedef int16 pri16;
typedef uint32 umsg32;
typedef uint16 intmask;
typedef int32 ibid32;
typedef int32 dbid32;
typedef int32 syscall;
typedef int32 devcall;
typedef int32 shellcmd;
typedef int32 process;
typedef void interrupt;
typedef int32 status;
typedef uint32 marker[1];
# 61 "C:/Users/mol/Desktop/School/Graduate-School/CIS657/FINAL/XINU SIM/output/include/xinu.h" 2
# 1 "C:/Users/mol/Desktop/School/Graduate-School/CIS657/FINAL/XINU SIM/output/include/memory.h" 1
# 32 "C:/Users/mol/Desktop/School/Graduate-School/CIS657/FINAL/XINU SIM/output/include/memory.h"
struct memblk {
 struct memblk *mnext;
 uint32 mlength;
typedef struct bios32 {
    unsigned long signature;
typedef __builtin_va_list va_list;
typedef void exchandler;
typedef int message;
typedef int bool32;

/* Constant definitions */

#endif /* _XINU_STDDEFS_H_ */
