/* xinu_includes.h - Primary include file for XINU simulation
 * Generated by {{ generator }}
 * Generated on: {{ timestamp }}
 * By user: {{ user }}
 */
#ifndef _XINU_INCLUDES_H_
#define _XINU_INCLUDES_H_

/* Include system standard libraries first */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include <ctype.h>
#include <time.h>

/* Then include our XINU-specific standard definitions */
#include "xinu_stddefs.h"
#include "xinu.h"
#include "xinu_sim_declarations.h"

/* Define FILE pointer compatibility with XINU's stream structure */
typedef FILE* xinu_FILE;

/* Process table */
extern struct procent {
    unsigned long prstate;   /* Process state */
    char *prstkbase;         /* Base of stack */
    int  prstklen;           /* Stack length */
    char prname[16];         /* Process name */
    int  prio;               /* Process priority */
    int  quantum;            /* Quantum (ticks until rescheduling) */
    int  ppid;               /* Parent pid */
    /* Add prdesc element needed by stdio functions */
    void *prdesc[3];         /* Standard I/O descriptors (stdin,stdout,stderr) */
} proctab[];

/* Define XINU I/O function pointer types */
typedef int (*xinu_putc_func_t)(int, int);
typedef int (*xinu_doscan_getc_func_t)(int);
typedef int (*xinu_doscan_ungetc_func_t)(int, int);
typedef int (*xinu_qsort_cmp_t)(const void*, const void*);

/* Standard C library compatibility functions */
extern int xinu_printf_sim_redirect(const char *format, ...);
extern int xinu_fprintf_sim_redirect(void *stream, const char *format, ...);
extern int xinu_sprintf_sim_redirect(char *buffer, const char *format, ...);
extern int xinu_scanf_sim_redirect(const char *format, ...);
extern int xinu_fscanf_sim_redirect(void *stream, const char *format, ...);
extern int xinu_sscanf_sim_redirect(const char *buffer, const char *format, ...);
extern int xinu_getchar_sim_redirect(void);
extern int xinu_putchar_sim_redirect(int c);
extern int xinu_fgetc_sim_redirect(void *stream);
extern char* xinu_fgets_sim_redirect(char *str, int num, void *stream);
extern int xinu_fputc_sim_redirect(int c, void *stream);
extern int xinu_fputs_sim_redirect(const char *str, void *stream);

/* Define redirects from XINU functions to standard C library */
#define printf xinu_printf_sim_redirect
#define fprintf xinu_fprintf_sim_redirect
#define sprintf xinu_sprintf_sim_redirect
#define scanf xinu_scanf_sim_redirect
#define fscanf xinu_fscanf_sim_redirect
#define sscanf xinu_sscanf_sim_redirect
#define getchar xinu_getchar_sim_redirect
#define putchar xinu_putchar_sim_redirect
#define fgetc xinu_fgetc_sim_redirect
#define fgets xinu_fgets_sim_redirect
#define fputc xinu_fputc_sim_redirect
#define fputs xinu_fputs_sim_redirect

/* External declarations for system variables */
extern pid32 currpid;        /* Currently executing process ID */
extern unsigned long clktime;/* Current time in seconds since boot */
extern unsigned long count1000;/* Milliseconds since last clock tick */

#endif /* _XINU_INCLUDES_H_ */