/* xinu_stddefs.h - Generated by xinu_generator.py
 * Generated on: 2025-06-16 15:36:25
 */
#ifndef _XINU_STDDEFS_H_
#define _XINU_STDDEFS_H_

/* Basic XINU type definitions */
typedef void exchandler;
typedef int message;

/* Add other basic XINU typedefs as needed */
#ifndef __int32_t_defined
typedef int int32;
#endif

#ifndef __uint32_t_defined
typedef unsigned int uint32;
#endif

typedef int bool32;
typedef int did32;

#endif /* _XINU_STDDEFS_H_ */
